import type { Metadata } from 'next'
import { Calistoga, Inter } from 'next/font/google'
import './globals.css'
import SideBar from './components/SideBar'
import TopBar from './components/TopBar'
import Footer from './components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex`}>
        <TopBar />
        <div className="fixed">
          <SideBar />
        </div>
        {children}
      </body>
    </html>
  )
}
